#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "zeroui"
name = "ZeroUI"
description.en = "A web user interface for a ZeroTier network controller"
description.fr = "Une interface utilisateur web pour un contrôleur de réseau ZeroTier"

version = "1.5.8~ynh1"

maintainers = ["tituspijean"]

[upstream]
# NB: Only the "license" key is mandatory. Remove entries for which there's no relevant data
license = "GPL-3.0-only"
code = "https://github.com/dec0dOS/zero-ui"

[integration]
yunohost = ">= 11.1.21"
architectures = "all"
multi_instance = false
ldap = false
sso = false
disk = "300M"
ram.build = "2G"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "admins"
    help.en = "Choose which group can administer the ZeroTier controller. Never select Visitors!"
    help.fr = "Choisissez quel group peut administrer le contrôleur ZeroTier. Ne sélectionnez jamais les Visiteurs !"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/dec0dOS/zero-ui/archive/refs/tags/v1.5.8.tar.gz"
        sha256 = "465ec7d0b90296720b6cbee8f2b4dfa03fdbfd525cbdf04a55d0754709ea71e0"

        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
